apiVersion: v1
kind: Service
metadata:
  name: {{ include "players.fullname" . }}
  annotations:
    konghq.com/connect-timeout: "2000"
    konghq.com/read-timeout: "2000"
    konghq.com/write-timeout: "2000"
    konghq.com/host-header: "{{ include "players.fullname" . }}.bets.svc"
    konghq.com/plugins: prometheus-players,players-logs
    ingress.kubernetes.io/service-upstream: "true"
  labels:
    {{- include "players.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "players.selectorLabels" . | nindent 4 }}
